name: tests

on:
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: uvicorn main:app --port 8000 &

      - run: sleep 3

      - run: pytest